language: objective-c
osx_image: xcode9.1
xcode_project: SchemaApplication.xcodeproj #3
xcode_scheme: SchemaApplication #4
xcode_sdk: iphonesimulator11.1 #5
script:
- xcodebuild -scheme 'SchemaApplication' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
- xcodebuild -scheme 'SchemaApplication' test | xcpretty -c
